# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2023, ARIES Embedded. All rights reserved.

obj-y	:= msrzfive.o
obj-y	+= ../../renesas/rzf-dev/rzf-dev_cpg.o
obj-y	+= ../../renesas/rzf-dev/rzf-dev_pfc.o
obj-y	+= ../../renesas/rzf-dev/rzf-dev_spi.o
