#
# board/aries/msrzg3s/Makefile
#
# Copyright (C) 2025 ARIES Embedded
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../../renesas/rcar-common/gen3-spl.o
else
obj-y	:= msrzg3s.o ../../renesas/rcar-common/common.o
endif
